### ISSUE TITLE
Example links are not working

### ISSUE THREAD

**Issue by jagru20** [vriajs/vria#1]
Hello, 

I wanted to try out VRIA on the website hosted by you via github. Unfortunately the links on the page do not work. They lead to a Error 404 page. Is this me or can there be anything done about this?

**Comment by PButcher** [comment]
I'll patch this asap, but you're right, the examples cannot currently be accessed directly from a URL on the GitHub pages version.

For now, you can navigate to the examples by clicking the examples button on the top right of the builder:

<img width="239" alt="Screenshot 2021-06-08 at 12 02 07" src="https://user-images.githubusercontent.com/1674115/121173992-5a6e0d00-c851-11eb-8dd9-56eb74da6502.png">

I will close this issue once the URL situation is sorted.

Thanks.

**Comment by PButcher** [comment]
This has now been fixed in a2a845666ffe7272136f476313258f9b2d71950e.

NPM Package bumped to 0.9.3: https://www.npmjs.com/package/vria
