### ISSUE TITLE
White screen on Magic Leap

### ISSUE THREAD

**Issue by tashfeenahmed** [vriajs/vria#2]
Hello 👋

I'm trying to run a [VRIA visualisation](https://tashfeenahmed.github.io/3dvis/vria/) using Magic Leap 1 but it shows a blank screen. I have also tried to run the [examples](https://vriajs.github.io/vria) – they seem to work fine on Chrome but not on Helio (Magic Leap's browser).

Can you please help me identify the problem?

Thanks~

**Comment by PButcher** [comment]
Thanks for posting the issue, happy to hear you're trying to use VRIA in your project! 

I have made a few fixes related to #1 in a2a845666ffe7272136f476313258f9b2d71950e which should also help to solve the problems you were experiencing.

Please let me know if that is the case, and if not, I'd like to dig into how we can get VRIA working correctly on the Magic Leap!

**Comment by tashfeenahmed** [comment]
Thank you so much @PButcher! I can confirm that this has been fixed and I can run VRIA on Helio 😊

**Comment by PButcher** [comment]
Result! Thanks a lot for testing.
